# CONFIG FILE

# Name of the experiment (a name for the results folder)
experiment_name: CH65

# Directory where sequencing data is stored (see README for details)
sequencing_data_dir: /n/holyscratch01/desai_lab/jeffjar/CH65_data/sequencing/
cytometry_data_dir: /n/holyscratch01/desai_lab/jeffjar/CH65_data/cytometry/

# Metadata files (see README for details)
sample_table_filename: metadata/sample_info_CH65.tsv
replicate_info_filename: metadata/replicate_info_CH65.tsv

# --------------------------
# Sequence info
# --------------------------

# Provide the ancestral '0' sequence and the evolved '1' sequence, in this case
# the UCA860 and CH65. This is not the amplicon, but rather
# just the sequence of the antibody construct (VL-GS-VH). The amino acid numbering starts at the
# specified residue number below.
sequence_begins_with_residue: 1
ancestral_seq: |
    CAGTCAGTGCTGACTCAACCACCATCCGTGAGTGTTGCCCCTGGCCAGACGGCTAGAATTACCTGCGGCGGTAACAACATTGGAAGTAAAAGTGTGCACTGGTACCAGCAGAAGCCAGGCCAGGCCCCTGTGCTGGTCGTCTATGATGATAGCGACCGGCCCTCAGGCATACCTGAGCGATTCTCTGGCTCCAACTCTGGGAACACGGCCACCCTGACCATCAGCAGGGTCGAAGCCGGGGATGAGGCCGACTATTACTGTCAGGTGTGGGATAGTAGTAGTGATCATGTGGTATTCGGCGGAGGGACCAAGCTGACCGTCCTAGGTGGTGGAGGCGGATCAGGCGGTGGAGGTTCTGGCGGAGGAGGTAGTCAGGTGCAGCTGGTGCAGTCTGGGGCTGAGGTGAAGAAGCCTGGGGCCTCAGTGAAGGTCAGCTGCAAGGCTTCTGGATACACCTTCACCGGCTACTATATGCACTGGGTGCGACAGGCCCCTGGACAAGGGCTTGAGTGGATGGGATGGATCAACCCTAACAGTGGTGGCACAAACTATGCACAGAAGTTTCAGGGCTGGGTCACCATGACCAGGGACACGTCCATCAGCACAGCCTACATGGAGCTGAGCAGGCTGAGATCTGACGACACGGCCGTGTATTACTGTGCCCGTGGAGGCCTGGAACCACGTAGTGTTGATTACTACTACTATGGCATGGATGTTTGGGGTCAAGGAACAACAGTTACCGTTTCTTCA
descendant_seq: |
    CAGTCAGTGCTGACTCAACCACCATCCGTGAGTGTTGCCCCTGGCCAGACGGCTAGAATTACCTGCGGCGGTAACgatATTGGAcggAAAAGTGTGCACTGGaatCAGCAGAAGCCAGGCCAGGCCCCTGTGCTGGTCGTCtgctacGATAGCGACagaCCCTCAGGCATACCTGAGCGATTCTCTGGCTCCAACTCTGGGAACACGGCCACCCTGACCATCAGCAGGGTCGAAGCCGGGGATGAGGCCGACTATTACTGTCAGGTGTGGGATAGTAGTAGTGATCATGTGatcTTCGGCGGAGGGACCAAGCTGACCGTCCTAGGTGGTGGAGGCGGATCAGGCGGTGGAGGTTCTGGCGGAGGAGGTAGTCAGGTGCAGCTGGTGCAGTCTGGGGCTGAGGTGAAGAAGCCTGGGGCCTCAGTGAAGGTCAGCTGCAAGGCTTCTGGATACACCTTCACCgatTACcacatcaatTGGGTGCGACAGGCCCCTGGACAAGGGCTTGAGTGGATGGGATGGATCcatCCTAACAGTGGTgatACAAACTATGCACAGAAGTTTCAGGGCTGGGTCACCATGACCAGGGACACGTCCATCAGCACAGCCTACATGGAGgtcaatggaCTGaagTCTGACGACACGGCCGTGTATTACTGTGCCCGTGGAGGCCTGGAACCACGTAGTGTTGATTACTACTACTATGGCATGGATGTTTGGGGTCAAGGAACAACAGTTACCGTTTCTTCA
    
# The pipeline automatically detects the mutations present in the gene sequences,
# but for good measure, they are explicitly listed here. The scripts will throw
# an error if this information is not consistent
mutation_names: [ N26D, S29R, Y35N, Y48C, D49Y, V98I, G155D, Y157H, M158I, H159N, N176H, G181D, L207V, S208N, R209G, R211K ]
num_mutations: 16

# Some of the mutations are also `synomously encoded' at other residue positions
# so that they lie in the illumina read part of the amplicon. In this case
synonymously_coded_mutations:
    - mutation_name: V98I
      synonomous_position: 53
      codon_0: CGG
      codon_1: AGA
      
# --------------------------
# Primers and NGS sequencing
# --------------------------

num_mutations_on_forward_read: 6
# The part of the forward primer which anneals to the plasmid
foward_read_annealing_seq: CTGGCCAGACGGCTAG
# Number of bp between 5' end of gene sequence and 5' end of the annealing primer sequence
# Negative means amplicon starts before gene, positive means after
forward_read_starting_offset: 40

num_mutations_on_reverse_read: 10
# The reverse complement of the part of the reverse primer which anneals to plasmid
reverse_read_annealing_seq: CCTCCACGGGCACAG
# Number of bp between 3' end of annealing sequence and the 3' end of gene sequence
# Negative means amplicon ends after gene, positive means before
reverse_read_starting_offset: 79

umi_length: 8

row_inline_indices:
    - TACCTGA
    - AGAACCAT
    - ACCGTTGAC
    - GCAAGCTGTT
    - TCGGTGGTACG
    - GTTCAACCGATT
    - CGTACAA
    - GAGATCAC
    
col_inline_indices:
    - TTGATCG
    - CATTCTCGAG
    - CCTTAGTACTA
    - AGTGGAATACCT
    - GGTATCA
    - GATGTCCT
    - CTCATCCAG
    - GACGGAACTC
    - ATCGCAGGCAT
    - TCACGACTAGTA

# --------------------------
# Data processing
# --------------------------



# Debug mode, set to False when running the full experiment
debug_mode: True
max_reads_per_file_if_debugging: 50

# parameters for the sequence parsing
num_substitutions_tolerated_in_inline_idx: 0
num_substitutions_tolerated_per_ten_bp: 0.3
are_indels_tolerated_in_primers: True

# parameters for the Kd inference
bounds_log10Kd_min: -14
bounds_log10Kd_max: -5
bounds_A_min: 100
bounds_A_max: 1000000
bounds_B_min: 1
bounds_B_max: 100000

# The plotting codes often throw bugs so here's a flag to just skip it
do_plots: False
